pref("extensions.redditmutilator.blocknsfw", true);
pref("extensions.redditmutilator.blockdomains", "");
pref("extensions.redditmutilator.blockusers", "");
pref("extensions.redditmutilator.hideshare", false);
pref("extensions.redditmutilator.hidesave", false);
pref("extensions.redditmutilator.hidehide", false);
pref("extensions.redditmutilator.hidereport", false);
pref("extensions.redditmutilator.hidecreatebox", false);
pref("extensions.redditmutilator.hidesubmitbox", false);
pref("extensions.redditmutilator.hidemodbox", false);
pref("extensions.redditmutilator.hiderecentbox", false);
pref("extensions.redditmutilator.hidesubredditbar", false);
pref("extensions.redditmutilator.hidesearchbox", false);
pref("extensions.redditmutilator.userunity", true);
pref("extensions.redditmutilator.blockcommentusers", "");
pref("extensions.redditmutilator.hideinfobox", false);
pref("extensions.redditmutilator.whitelistsubreddits", true);
pref("extensions.redditmutilator.whitelistedsubreddits", "");

// https://developer.mozilla.org/en/Localizing_extension_descriptions
pref("extensions.{a00b4d87-e032-49c0-ba21-abbe079b51ae}.description", "chrome://redditmutilator/locale/overlay.properties");
